### ISSUE TITLE
build error : 'inttypes.h' file not found

### ISSUE THREAD

**Issue by easyfrog** [aheissenberger/vlang-wasm-example#1]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/10724325/167344473-9da74bd2-fe16-4ce9-af69-b98bcf7c13df.png">

`MacOS 12.3.1`

```sh
#!/bin/sh
# CLANG_CMD="/Users/easyfrog/libs/v-wasm/wasi-sdk-14.0/bin/clang"
CLANG_CMD="/usr/bin/clang"
# export $PATH=$PATH:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
FILE=$1
DEBUG=$2 # -g
v "${FILE}.v" $DEBUG -o "${FILE}.c"
$CLANG_CMD $DEBUG -w -O3 -D__linux__ \
        -target wasm32-unknown-wasi \
        --sysroot "$WASI_SDK/share/wasi-sysroot" \
        -D_WASI_EMULATED_SIGNAL \
        -lwasi-emulated-signal \
        -Iwasm_include \
        -Wl,--allow-undefined \
        -o "${FILE}.wasm" \
        "${FILE}.c"
```

**Comment by aheissenberger** [comment]
@easyfrog I am currently not using vlang and this project was my result of trying to get this working a year ago on an older macOS. Maybe you should ask in the vlang community about the best current process to compile vlang to wasm.

**Comment by easyfrog** [comment]
> @easyfrog I am currently not using vlang and this project was my result of trying to get this working a year ago on an older macOS. Maybe you should ask in the vlang community about the best current process to compile vlang to wasm.

Thanks for your answer~
